### ISSUE TITLE
ERROR: Failure in AnalysisManager.run Again

### ISSUE THREAD

**Issue by therealdreg** [brad-sp/cuckoomon-modified#19]
Hi, after install the community ./community.py -a -w -f I have this error:

2015-06-08 09:42:52,343 [lib.cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
2015-06-08 09:43:07,486 [requests.packages.urllib3.connectionpool] INFO: Starting new HTTPS connection (1): www.virustotal.com
2015-06-08 09:43:10,839 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 413, in run
    self.process_results()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 362, in process_results
    RunSignatures(task_id=self.task.id, results=results).run()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/plugins.py", line 391, in run
    self._check_signature_version(sig) and (not sig.filter_analysistypes or self.results["target"]["category"] in sig.filter_analysistypes)]
  File "/home/cuckoo/cuckoo-modified/modules/signatures/andromeda_apis.py", line 31, in __init__
    self.sysvolserial = self.get_environ_entry(self.get_initial_process, "SystemVolumeSerialNumber")
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/common/abstracts.py", line 1174, in get_environ_entry
    if not proc or not "environ" in proc or not env_name in proc["environ"]:
TypeError: argument of type 'instancemethod' is not iterable

**Comment by David-Reguera-Garcia-Dreg** [comment]
Here the BSON files: http://server.fr33project.org/cuckoo/logs/

**Comment by brad-sp** [comment]
Should be fixed now, thanks!  Requires another ./community.py update
